Notes to self:

how to retrieve crop times
should I incorporate first and last points?

In [2]:
%matplotlib widget
%load_ext autoreload
%autoreload 2
from src.folder_handler import *
from src.cort_processor import *
from src.tdt_support import *
from src.plotter import *
from src.decoders import *
import pickle
import scipy as spicy
import numpy as np
import matplotlib.pyplot as plt
from  matplotlib.colors import LinearSegmentedColormap
from src.wiener_filter import *
from matplotlib.pyplot import cm

In [3]:
session512 = CortProcessor('/home/grant/oobootoo/rat-fes/data/annie5-12')

read from t=0s to t=186.82s
read from t=0s to t=164.93s


In [4]:
session512.process()

(array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 20., 20.,  0.],
        [ 0., 20., 20., ..., 20., 20., 20.],
        ...,
        [ 0.,  0.,  0., ..., 20., 40., 40.],
        [40.,  0.,  0., ...,  0.,  0.,  0.],
        [40.,  0., 20., ..., 20.,  0., 20.]]),
 array([[ 40.51699572,  42.20588215,  92.11393015, ..., 103.26517599,
          83.11518502, 134.56248046],
        [ 66.65535071,  80.9848782 ,  85.76827785, ..., 128.31902597,
          76.23651019, 162.90207555],
        [ 70.70562606,  96.67307096,  85.98258164, ..., 126.19378951,
          77.09433774, 158.66407895],
        ...,
        [ 41.99036523,  47.99714   ,  90.34380609, ...,  76.85358056,
          94.47954229, 113.40009338],
        [ 45.12710738,  52.09725454,  89.38768704, ...,  81.9092561 ,
          92.6822898 , 119.97226002],
        [ 40.79986548,  45.5802486 ,  91.30910479, ...,  71.35645255,
          93.51400329, 109.05486824]]))

In [5]:
session512.data['angles']

[array([[ 40.51699572,  42.20588215,  92.11393015, ..., 103.26517599,
          83.11518502, 134.56248046],
        [ 66.65535071,  80.9848782 ,  85.76827785, ..., 128.31902597,
          76.23651019, 162.90207555],
        [ 70.70562606,  96.67307096,  85.98258164, ..., 126.19378951,
          77.09433774, 158.66407895],
        ...,
        [ 49.06484473,  51.76534126, 100.88736032, ...,  49.784722  ,
          76.99608756, 102.25328454],
        [ 38.42596656,  42.58741962,  99.69128634, ...,  57.77336204,
          85.11690152, 105.85440279],
        [ 19.34037702,  27.92536214,  99.45780069, ...,  69.14260002,
          90.37203818, 104.62049694]]),
 array([[ 61.153092  ,  75.86803041,  82.1825519 , ..., 109.52061515,
          86.92250575, 148.66064798],
        [ 71.25177027,  96.05110557,  68.24835481, ..., 128.93038979,
          80.90565523, 154.69007466],
        [ 52.53935603,  79.81225416,  67.39674691, ..., 115.75385401,
          84.71462311, 137.00578132],
        ...,


In [6]:
rates = session512.data['rates']
angles = session512.data['angles']
coords = session512.data['coords']

In [7]:
print(len(coords))

2


In [8]:
len(rates[0])

2962

In [9]:
(angles[0].shape)[0]


2962

In [10]:
coords[0].shape


(2962, 17, 3)

In [11]:
session512.data.keys()

dict_keys(['bodyparts', 'angle_names', 'rates', 'coords', 'angles'])

In [12]:
session512.data["angle_names"]

['ankle', 'knee', 'hip', 'limbfoot', 'elbow', 'shoulder', 'forelimb']

In [16]:
# print(len(session512.data['angles']))
# print(session512.data['angles'][0].shape)
# print(session512.data['angles'][1].shape)
# print(session512.data['angles'][2].shape)
# print(session512.data['angles'][3].shape)

In [17]:
session512.data['bodyparts']

['toe',
 'MTP',
 'ankle',
 'knee',
 'pelvis bottom',
 'hip',
 'pelvis top',
 'finger',
 'knuckle',
 'wrist',
 'elbow',
 'shoulder',
 'scapula',
 'x1',
 'x2',
 'y1',
 'y2']

In [18]:
new_rates = []
new_angles = []
new_coords = []
for i in range(len(rates)):
    size_we_want = int(rates[i].shape[0] / 2)
    temp_rate = rates[i][:size_we_want,:]
    new_rates.append(temp_rate)
    temp_angle = angles[i][:size_we_want,:]
    new_angles.append(temp_angle)
    temp_coord = coords[i][:size_we_want,:, :]
    new_coords.append(temp_coord)

In [19]:
session512.decode_angles?

Signature: session512.decode_angles(X=None, Y=None)
Docstring:
takes list of rates, angles, then using a wiener filter to decode. 
if no parameters are passed, uses data['rates'] and data['angles']

returns best_h, vaf (array of all angles and all folds), test_x (the
x test set that had best performance, and test_y (the y test set that
had best formance)
File:      /mnt/c/oobootoo/rat-fes/src/cort_processor.py
Type:      method


In [20]:
h, vaf, x_test, y_test = session512.decode_angles(X=new_rates, Y=new_angles)

In [22]:
print(h.shape)

(321, 7)


In [ ]:
type(new_angles)

In [ ]:
new_angles

In [ ]:
h.shape

In [ ]:
vaf.shape

In [ ]:
vaf[0,:]

In [ ]:
np.average(vaf,axis=1)

In [ ]:
plot_wiener_filter_predic?

In [ ]:
x_test.shape

In [ ]:
# plot_wiener_filter_predic(x_test, y_test[:,0], h[:,0])
# plot_wiener_filter_predic(x_test, y_test[:,1], h[:,1])
# plot_wiener_filter_predic(x_test, y_test[:,2], h[:,2])
# plot_wiener_filter_predic(x_test, y_test[:,3], h[:,3])
# plot_wiener_filter_predic(x_test, y_test[:,4], h[:,4])
# plot_wiener_filter_predic(x_test, y_test[:,5], h[:,5])
# plot_wiener_filter_predic(x_test, y_test[:,6], h[:,6])

In [ ]:
def stance_swing_dd(toe_height):
    # peaks = extract_peaks(toe_height, 12)
    peaks, nada = find_peaks(toe_height, prominence=10)
    peaks = np.append(peaks, np.size(toe_height))
    peaks = np.insert(peaks, 0, 0)
    ss_list = []

    for i in range(np.size(peaks)-1):
        end=peaks[i+1]
        start=peaks[i]

        gait = toe_height[start:end]
        dx = np.gradient(gait)
        ddx = np.gradient(dx)

        ddx_peaks, nada = find_peaks(ddx, 0.02)
        if np.size(ddx_peaks) == 2:
            ss = np.ones(np.size(gait), dtype=bool)
            ss[ddx_peaks[0]:ddx_peaks[1]] = 0
        else:
            minny = np.amin(gait)
            ss = gait>minny+2

        ss_list.append(ss)

    stance_swing = np.hstack(ss_list)
    return stance_swing

In [ ]:
session512.process_toe_height()

In [ ]:
toe = session512.data['toe_height']

In [ ]:
len(toe)

In [ ]:
toeh = np.hstack(toe)

In [ ]:
toeh.shape


In [ ]:
ss = stance_swing_dd(toeh)

In [ ]:
# fig0 = plt.figure()
# ax0 = fig0.add_subplot(111)
# ax0.plot(ss)

In [ ]:
# plot_wiener_filter_predic(x_test, y_test[:,1], h[:,1])
# plt.show()

In [ ]:
print(x_test.shape)
print(x_test)

In [ ]:
print(y_test[:,1].shape)
min_y1 = min(y_test[:,1])
max_y1 = max(y_test[:,1])
print(min_y1)
print(max_y1)
print(max_y1-min_y1)

In [ ]:
print(h[:,1].shape)
# print(h[:,1])

In [ ]:
def plot_wiener_filter_predic_malleable(test_x, test_y, h):
    predic_y = test_wiener_filter(test_x, h)
    vaffy = vaf(test_y, predic_y)
    
    samples = np.shape(test_y)[0]

    ts = np.linspace(0, (samples*50)/1000,
            samples)

    fig, ax = plt.subplots()
    ax.set_title(f'vaf:{vaffy}')
    ax.plot(ts, test_y, c='black')
    ax.plot(ts, predic_y, c='red')

In [ ]:
def test_wiener_filter_malleable(x, H):
    """
    To get predictions from input data x with linear decoder
    x: input data
    H: parameter vector obtained by training
    """
    x_plus_bias = np.c_[np.ones((np.size(x, 0), 1)), x]
    y_pred = np.dot(x_plus_bias, H)
    return y_pred    

In [ ]:
y1_pred = test_wiener_filter_malleable(x_test, h[:,1])
y1_actual = y_test[:,1]

In [ ]:
print(y1_pred.shape)
print(np.shape(y1_actual)[0])

In [ ]:
ts = np.linspace(0, (np.shape(y1_actual)[0]*50)/1000,np.shape(y1_actual)[0])

In [ ]:
peaks_y1, _ = spicy.signal.find_peaks(y1_actual, prominence=10, height = np.mean(y1_actual))
peaks_y1 = np.concatenate([[0],peaks_y1,[np.shape(y1_actual)[0]-1]])

In [ ]:
# fig, ax = plt.subplots()
# ax.plot(ts, y1_actual, c='black')
# ax.scatter(ts[peaks_y1], y1_actual[peaks_y1], c='r')

In [ ]:
y1_copy = y1_actual.copy()
for i in range(0,peaks_y1.shape[0]-1):
    for ii in range(0, peaks_y1[i+1]-peaks_y1[i]):
        y1_copy[peaks_y1[i]+ii] = ii*360/(peaks_y1[i+1]-peaks_y1[i])
y1_copy[peaks_y1[-1]] = 0

In [ ]:
# fig, ax = plt.subplots()
# ax.plot(ts, y1_copy, c='black')

In [ ]:
y1_cos = (np.cos(y1_copy*np.pi/180)*np.mean(y1_actual)/2)+np.mean(y1_actual)

In [ ]:
# fig, ax = plt.subplots()
# ax.plot(ts, y1_cos, c='blue')
# ax.plot(ts, y1_actual, c='black')


In [ ]:
peaks_y1_pred, _ = spicy.signal.find_peaks(y1_pred, prominence=10, height = np.mean(y1_pred))
peaks_y1_pred = np.concatenate([[0],peaks_y1_pred,[np.shape(y1_pred)[0]-1]])

In [ ]:
# fig, ax = plt.subplots()
# ax.plot(ts, y1_pred, c='red')
# ax.scatter(ts[peaks_y1_pred], y1_pred[peaks_y1_pred], c='k')

In [ ]:
y1_pred_copy = y1_pred.copy()
for i in range(0,peaks_y1_pred.shape[0]-1):
    for ii in range(0, peaks_y1_pred[i+1]-peaks_y1_pred[i]):
        y1_pred_copy[peaks_y1_pred[i]+ii] = ii*360/(peaks_y1_pred[i+1]-peaks_y1_pred[i])
y1_pred_copy[peaks_y1_pred[-1]] = 0

In [ ]:
y1_pred_cos = (np.cos(y1_pred_copy*np.pi/180)*np.mean(y1_pred)/2)+np.mean(y1_pred)

In [ ]:
fig, axs = plt.subplots(4, 2, figsize=(16,20))
axs[0, 0].set_title('y_actual peaks')
axs[0,0].plot(ts, y1_actual, c='black')
axs[0,0].scatter(ts[peaks_y1], y1_actual[peaks_y1], c='blue')

axs[0, 1].set_title('y_pred peaks')
axs[0,1].plot(ts, y1_pred, c='red')
axs[0,1].scatter(ts[peaks_y1_pred], y1_pred[peaks_y1_pred], c='darkgoldenrod')

axs[1, 0].set_title('y_test phase')
axs[1,0].plot(ts, y1_copy, c='blue')

axs[1, 1].set_title('y_pred phase')
axs[1,1].plot(ts, y1_pred_copy, c='darkgoldenrod')

axs[2,0].set_title('cosine aligned y_test')
axs[2,0].plot(ts, y1_cos, c='blue')
axs[2,0].plot(ts, y1_actual, c='black')

axs[2, 1].set_title('cosine aligned y_pred')
axs[2,1].plot(ts, y1_pred_cos, c='darkgoldenrod')
axs[2,1].plot(ts, y1_pred, c='red')

axs[3, 0].set_title("predicted vs. actual raw")
axs[3,0].plot(ts, y1_pred, c='red')
axs[3,0].plot(ts, y1_actual, c='black')

axs[3, 1].set_title('cosine aligned predicted vs. actual')
axs[3,1].plot(ts, y1_pred_cos, c='red')
axs[3,1].plot(ts, y1_cos, c='black')
# axs[3,1].plot(ts, y1_pred_cos, c='darkgoldenrod')
# axs[3,1].plot(ts, y1_cos, c='blue')
fig.tight_layout()

In [ ]:
improved_score = vaf(y1_cos, y1_pred_cos)
previous_score = vaf(y1_actual, y1_pred)
# print("New VAF:")
# print(improved_score)
# print("Improvement:")
# print(100*(improved_score-previous_score)/previous_score,'%')